modLoader="javafml" #mandatory
loaderVersion="[26,)" #mandatory
issueTrackerURL="https://github.com/BuiltBrokenModding/SBM-Jukebox/issues"
displayURL="http://minecraft.curseforge.com/projects/sbm-jukebox"
authors="StrikerRocker"

[[mods]] #mandatory
modId="jukebox" #mandatory
version="0.0.1" #mandatory
displayName="[SBM] Jukebox" #mandatory
description='''Simple mod that makes the jukebox inventory accessible''' #mandatory

[[dependencies.jukebox]]
    modId="forge"
    mandatory=true
    versionRange="[26,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.jukebox]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.14.2]"
    ordering="NONE"
    side="BOTH"